control_dt: 0.02

msg_type: "go"     # "hg" or "go"
imu_type: "torso"    # "torso" or "pelvis"
torso_idx: 6

weak_motor: [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

lowcmd_topic: "rt/lowcmd"
lowstate_topic: "rt/lowstate"

policy_path: "policy/h1/policy.pt"
history_length: 10

joint2motor_idx: [7,    8,    6,    3,    0,     16,   12,  4,    1,    17,   13,   5,    2,    18,   14,   10,   11,   19,   15]
kps:             [150., 150., 200., 150., 150.,  40.,  40., 200., 200., 40.,  40.,  200., 200., 40.,  40.,  40.,  40.,  40.,  40.]
kds:                 [5., 5., 5., 5., 5., 2., 2., 5., 5., 2., 2., 5., 5., 2., 2., 2., 2., 2., 2.]
default_angles:      [0.00,  0.00,  0.00,  0.00,  0.00,  0.20,  0.20, -0.28, -0.28,  0.00,  0.00,  0.79,  0.79,  0.00,  0.00, -0.52, -0.52,  0.32,  0.32]

ang_vel_scale: 1.0
dof_pos_scale: 1.0
dof_vel_scale: 1.0
action_scale: 0.25
cmd_scale: [1.0, 1.0, 1.0]
num_actions: 19
num_obs: 66

cmd_range: {lin_vel_x: [-0.4, 0.8], lin_vel_y: [-0.5, 0.5], ang_vel_z: [-1.57, 1.57]}
