control_dt: 0.02

msg_type: "go"     # "hg" or "go"
imu_type: "torso"    # "torso" or "pelvis"
torso_idx: 6

weak_motor: [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

lowcmd_topic: "rt/lowcmd"
lowstate_topic: "rt/lowstate"

policy_path: "policy/h1/policy.pt"
history_length: 15

leg_joint2motor_idx: [7,   8,    6,    3,    0,   16,   12,   4,     1,    17,   13,   5,    2,    18,   14,  10,   11,  19,  15]
kps:                 [200, 200,  300,  200,  200, 100,  100,  200,   200,  100,  100,  300,  300,  50,   50,  40,   40,  50,  50]
kds:                 [5,   5,    6,    5,    5,   2,    2,    5,     5,    2,    2,    6,    6,     2,   2,   2,    2,   2,   2]
default_angles:      [0,   0,    0,    0,    0,   0,    0,   -0.4,  -0.4,  0,    0,    0.8,  0.8,   0,   0,  -0.4, -0.4, 0,   0]

ang_vel_scale: 1.0
dof_pos_scale: 1.0
dof_vel_scale: 1.0
action_scale: 0.25
cmd_scale: [1.0, 1.0, 1.0]
num_actions: 19
num_obs: 66

cmd_range: {lin_vel_x: [-0.4, 0.8], lin_vel_y: [-0.35, 0.35], ang_vel_z: [-1.0, 1.0]}
